<?php
namespace app\controller;

use think\Controller;
use think\facade\Request;

class Api extends Controller
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        header("Access-Control-Allow-Origin: *");

        //token验证入口
        //不要在意，只是功能预留而已
        $token = Request::header('Authorization',null);
        if(!$token){
            $this->result( sha1($token),403,'验证失败，禁止非法访问！','json');
        }
    }
}
