<?php
namespace app\index\controller;

use app\index\model\Authorize;
use think\ViewController;

class Index extends ViewController
{
    /**
     * 全局继承
     * @throws \think\db\exception\DataNotFoundException
     * @throws \think\db\exception\ModelNotFoundException
     * @throws \think\exception\DbException
     */
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $authorized = new Authorize();
        $menus = $authorized->getList(2);
        $this->assign(['menus'=>$menus]);
       // $authorized->resetAuthorize();
    }

    public function index()
    {
        return $this->fetch('/index');
    }
    public function components(){
        return $this->fetch('/components');
    }
}
