<?php
/**
 * Created by PhpStorm.
 * User: top-dante
 * Date: 2019/3/16
 * Time: 19:18
 */

namespace app\controller;

use app\model\Authorize;


use think\ViewController;

class Base extends ViewController
{
    /**
     * 全局继承
     * @throws \think\db\exception\DataNotFoundException
     * @throws \think\db\exception\ModelNotFoundException
     * @throws \think\exception\DbException
     */
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $authorized = new Authorize();
        $menus = $authorized->getList(2);
        $location = $authorized->getLocation();
       $this->assign(['menus'=>$menus,'menu'=>$location]);
    }
}