<?php
namespace app\controller;

use app\model\Authorize;
use think\facade\Cache;
use think\ViewController;

class Index extends ViewController
{
    /**
     * 全局继承
     * @throws \think\db\exception\DataNotFoundException
     * @throws \think\db\exception\ModelNotFoundException
     * @throws \think\exception\DbException
     */
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $authorized = new Authorize();
        $menus = $authorized->getList(2);
        $this->assign(['menus'=>$menus]);
       // $authorized->resetAuthorize();
    }

    public function index()
    {
        return $this->fetch('/index');
    }
    public function components(){
        return $this->fetch('/components');
    }

    /**
     * 清除缓存
     */
    public function clear_cache(){
        Cache::clear();
        $this->result('',200,'缓存清除成功，正在为您刷新页面');
    }
}
