<?php
/**
 * Created by PhpStorm.
 * User: top-dante
 * Date: 2019/3/14
 * Time: 22:44
 */

namespace app\controller;

use think\facade\Request;
use think\facade\Config;

class Projects extends Base
{
    /**
     * @throws \think\db\exception\DataNotFoundException
     * @throws \think\db\exception\ModelNotFoundException
     * @throws \think\exception\DbException
     */
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $member = new \app\model\Member();
        $userList = $member->getUserList();
        //读取配置文件项目状态
        $projectStatus = Config::get('app.projectStatus');

        $this->assign(['status'=> $projectStatus,'userlist'=>$userList]);
    }

    /**
     * 项目首页
     * @return mixed
     * @throws \think\exception\DbException
     */
    public function index()
    {
        $projectModel = new \app\model\Projects();
        //项目状态和紧急程度配置输出
        $level = $projectModel->projectLevel;
        $getStatus = Request::get('status', '', 'intval');
        $getInterval = Request::get('interval', '', 'intval');
        $subject = Request::get('subject', '', 'htmlentities');

        $map = [];
        //搜索描述
        if ($subject) {
            $map[] = ['p.subject', 'like', "%$subject%"];
        }
        //状态管理
        if ($getStatus) {
            $map[] = ['p.status', '=', $getStatus];
        }
        //时间判断
        if ($getInterval) {
            switch ($getInterval) {
                case 1:
                    $startTime = strtotime(date('Y-m-d 00:00:00', strtotime("-30 day")));
                    break;
                case 3:
                    $startTime = strtotime(date('Y-m-d 00:00:00', strtotime("-3 months")));
                    break;
                case 6:
                    $startTime = strtotime(date('Y-m-d 00:00:00', strtotime("-6 months")));
                    break;
                case 12:
                    $startTime = strtotime(date('Y-m-d 00:00:00', strtotime("-1 year")));
                    break;
                case 36:
                    $startTime = strtotime(date('Y-m-d 00:00:00', strtotime("-3 year")));
                    break;
                default:
                    $startTime = strtotime(date('Y-m-d 00:00:00', strtotime("-30 day")));
            }
            $map[] = ['p.dateline', 'between', $startTime . ',' . time()];
        }
        $list = $projectModel->getProjectsPage($map);
        $date = date('Y-m-d H:i:s', strtotime("+7 day"));
        $this->assign([
            'list' => $list,
            'date' => $date,
            'getStatus' => $getStatus,
            'interval' => $getInterval,
            'level' => $level]
        );

        return $this->fetch();
    }
}