<?php
namespace app\api\controller;

use think\Controller;
header("Access-Control-Allow-Origin: *");
class Api extends Controller
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        header("Access-Control-Allow-Origin: *");
    }
}
