<?php
/**
 * Created by PhpStorm.
 * User: top-dante
 * Date: 2019/3/1
 * Time: 11:03
 */

namespace app\api\controller;


use think\Controller;

class Auth extends Controller
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        header("Access-Control-Allow-Origin: *");
    }
}